name: Go CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24', '1.23']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Unit Tests with Coverage
      run: go test -v ./... --timeout 5m -cover -tags unit_test
    - name: Integration Tests with Coverage
      run: go test -v ./... --timeout 15m -cover -tags integration_test
    - name: E2E Tests with Coverage
      run: go test -v ./... --timeout 60m -cover -tags e2e_test
