name: Go CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Unit Tests with Coverage
        run: go test -v ./... --timeout 5m -tags unit_test

      - name: Integration Tests with Coverage
        run: go test -v ./... --timeout 15m -tags integration_test

      - name: E2E Tests with Coverage
        run: go test -v ./... --timeout 60m -tags e2e_test
